config/routes.rb
Rails.application.routes.draw do


  devise_for :customers, path: :me, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }


  root to: 'public/homes#top'




  scope module: :public do
    # get 'customer/edit' => 'customers#edit'
    # patch 'customer/edit' => 'customers#update'
    get 'about' => 'homes#about'
    get 'orders/complete' => 'orders#complete'
    post 'orders/confirm' => 'orders#confirm'
    resources :orders, only: [:new, :index, :show, :create]
    resources :cart_items, only: [:index, :create, :update, :destroy]do
      delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    end
    resources :items, only: [:show, :index] do
      resources :reviews, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :deliveries, only: [:index, :destroy, :edit, :update, :create]
    resource :customers, only: [:show,:edit,:update] do
      get :favorites
    end

    patch 'customers/withdraw' => 'customers#withdraw'
    get 'customers/quit' => 'customers#quit'
  end



  namespace :admin do
    get '/' => 'homes#top'
    resources :orders, only: [:show, :update]
    resources :genres, only: [:index, :edit, :update, :create]
    resources :items, only: [:index, :show, :new, :edit, :update, :create]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :order_details, only: [:update]
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :deliveries
  has_many :cart_items
  has_many :orders
  has_many :items, through: :cart_items
  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy


  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。' }
  validates :first_name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。' }
  VALID_POSTCODE_REGEX = /\A\d{7}\z/
  validates :postcode, presence: true, format: { with: VALID_POSTCODE_REGEX }
  validates :address, presence: true
  VALID_PHONE_NUMBER_REGEX = /\A0(\d{1}[-(]?\d{4}|\d{2}[-(]?\d{3}|\d{3}[-(]?\d{2}|\d{4}[-(]?\d{1})[-)]?\d{4}\z|\A0[5789]0[-]?\d{4}[-]?\d{4}\z/
  validates :phone_number, presence: true, format: { with: VALID_PHONE_NUMBER_REGEX }
  validates :email, presence: true, uniqueness: true
  validates :encrypted_password, presence: true

  def full_name
    self.last_name + self.first_name
  end

  def full_address
     '〒' + postcode + ' ' + address
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  layout 'admin/application'
  def index
    @customers = Customer.all.page(params[:page]).per(6)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:notice] = "#{@customer.full_name}さんの会員情報を更新しました"
      redirect_to admin_customer_path(@customer)
    else
      render "edit"
    end
  end


  def order_index
    @customer = Customer.find(params[:customer_id])
    if params[:status] == "ichiran"
      @orders = @customers.orders.page(params[:page]).per(10)
    elsif params[:status]
      @order_statuses = @customer.orders.where(status: params[:status])
      @orders = @order_statuses.page(params[:page]).per(10)
    else
      @orders = @customer.orders.page(params[:page]).per(10)
    end
  end
  private

  def customer_params
    params.require(:customer).permit(:is_deleted)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <h3><%= @customer.last_name+@customer.first_name %>さんの会員情報編集</h3>
  
</div>
<div class="container">
  <div style="width:90%; margin:auto;">
    <%= form_with model:@customer, url: admin_customer_path(@customer), method: :patch do |f| %>
      <div class="form-group row">
        <label class="col-3">会員ID</label>
        <label class="col-3"><%= @customer.id %></label>
      </div>
      <div class="form-group row">
        <%= f.label :氏名, class: "col-3" %>
          <%= f.text_field :last_name, autocomplete: "last_name", class: "form-control col-3 mr-3" %>
          <%= f.text_field :first_name, autocomplete: "first_name", class: "form-control col-3" %>
      </div>

      <div class="form-group row">
        <%= f.label :フリガナ, class: "col-3" %>
        <%= f.text_field :last_name_kana, autocomplete: "last_name_kana", class: "form-control col-3 mr-3" %>
        <%= f.text_field :first_name_kana, autocomplete: "first_name_kana", class: "form-control col-3" %>
      </div>

      <div class="form-group row">
        <%= f.label :postcode, '郵便番号', class: "col-3" %>
        <%= f.text_field :postcode, autocomplete: "postcode", class: "form-control col-3" %>
      </div>

      <div class="form-group row">
        <%= f.label :address, '住所', class: "col-3" %>
        <%= f.text_field :address, autocomplete: "address", class: "form-control col-6" %>
      </div>

      <div class="form-group row">
        <%= f.label :phone_number, '電話番号', class: "col-3" %>
        <%= f.text_field :phone_number, class: "form-control col-3" %>
      </div>

      <div class="form-group row">
        <%= f.label :email, 'メールアドレス', class: "col-3" %>
        <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control col-3" %>
      </div>

      <div class="form-gropu row">
        <%= f.label :is_deleted, '会員ステータス', class: "col-3" %>
        <div class="custom-control custom-radio">
          <%= f.radio_button :is_deleted, false %> <%= f.label :is_active, "有効", class:"mr-3" %>
          <%= f.radio_button :is_deleted, true %> <%= f.label :is_active, "退会" %>
        </div>
      </div>

      <div class="actions mb-5 mt-5">
        <%= f.submit "変更を保存", class: "btn btn-success btn-lg col-2 offset-3" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/customers/index.html.erb
<containar>
  <div class="row  offset-1 mt-5 mb-3">
    <div class="col-lg-6">
      <h3 class="mini-title">会員一覧</h3>
    </div>
  </div>

  <div class="row text-center">
    <div class="col-lg-10 offset-1">
      <table class="table table-bordered table-hover table-background">
        <thead class="thead-dark">
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
            <tr onclick='window.location="<%= '/admin/customers/' + customer.id.to_s %>"' role="link">
              <td><%= customer.id %></td>
              <td>
                <%= customer.full_name %>

              </td>
              <td><%= customer.email %></td>
              <% if customer.is_deleted == true %>
                <td class="text-danger">退会</td>
              <% else %>
                <td class="text-success">有効</td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<containar>

app/views/admin/customers/show.html.erb
<containar>
  <div class="row justify-content-center mt-5">
    <h3 class="mini-title"><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h3>
  </div>
  <%= render 'layouts/errors', obj: @customer %>

  <div class="row justify-content-center">
    <div class="col-lg-6">
      <div class="row">
        <table class="table mx-5 table-bordered">
          <tr>
            <td class="col-lg-2 bg-dark text-light">会員ID</td>
            <td class="col-lg-4"><%= @customer.id %></td>
          </tr>
          <tr>
            <td class="bg-dark text-light">氏名</td>
            <td><%= @customer.full_name %></td>
          </tr>
          <tr>
            <td class="bg-dark text-light">フリガナ</td>
            <td><%= @customer.last_name_kana %> <%= @customer.first_name_kana %></td>
          </tr>
          <tr>
            <td class="bg-dark text-light">郵便番号</td>
            <td><%= @customer.postcode %></td>
          </tr>
          <tr>
            <td class="bg-dark text-light">住所</td>
            <td><%= @customer.address %></td>
          </tr>
          <tr>
            <td class="bg-dark text-light">電話番号</td>
            <td><%= @customer.phone_number %></td>
          </tr>
          <tr>
            <td class="bg-dark text-light">メールアドレス</td>
            <td><%= @customer.email %></td>
          </tr>
          <tr>
            <td class="bg-dark text-light">ステータス</td>
            <% if @customer.is_deleted == true %>
              <td>退会</td>
            <% else %>
              <td>有効</td>
            <% end %>
          </tr>
        </table>
      </div>
    </div>
  </div>

  <div class="row justify-content-center mt-3 mb-5">
    <%= link_to "編集する", edit_admin_customer_path(@customer), class: "btn btn-success mr-3" %>
    <%= link_to "#{@customer.full_name}さんの注文履歴一覧を見る", admin_path, class: "btn btn-primary" %>
  </div>
</containar>