config/routes.rb
Rails.application.routes.draw do


  devise_for :customers, path: :me, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }


  root to: 'public/homes#top'




  scope module: :public do
    # get 'customer/edit' => 'customers#edit'
    # patch 'customer/edit' => 'customers#update'
    get 'about' => 'homes#about'
    get 'orders/complete' => 'orders#complete'
    post 'orders/confirm' => 'orders#confirm'
    resources :orders, only: [:new, :index, :show, :create]
    resources :cart_items, only: [:index, :create, :update, :destroy]do
      delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    end
    resources :items, only: [:show, :index] do
      resources :reviews, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :deliveries, only: [:index, :destroy, :edit, :update, :create]
    resource :customers, only: [:show,:edit,:update] do
      get :favorites
    end

    patch 'customers/withdraw' => 'customers#withdraw'
    get 'customers/quit' => 'customers#quit'
  end



  namespace :admin do
    get '/' => 'homes#top'
    resources :orders, only: [:show, :update]
    resources :genres, only: [:index, :edit, :update, :create]
    resources :items, only: [:index, :show, :new, :edit, :update, :create]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :order_details, only: [:update]
  end

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details, dependent: :destroy
  has_many :items, through: :order_details

  enum status: { waiting: 0, confirm: 1, production: 2, preparation: 3, sent: 4 }
  enum pay_way: { credit_card: 0, transfer: 1 }


  validates :pay_way, presence: true
  validates :postage, presence: true
  VALID_POSTCODE_REGEX = /\A\d{7}\z/
  validates :postcode, presence: true, format: { with: VALID_POSTCODE_REGEX }
  validates :address, presence: true
  validates :address_name, presence: true
  validates :total_pay, presence: true


  def status_display
    status_i18n
  end

  def payment_method_display
    payment_method_i18n
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  layout 'admin/application'
  def show
    @order = Order.find(params[:id])
    @customer = Customer.find_by(params[order_id: @order.id])
    @order_detail = @order.order_details.find_by(order_id: @order.id)
  end

  def update
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @order.update(order_params)
    if @order.status == "confirm"
      @order_details.update_all('production_status = 1')
    end
    flash[:notice] = "注文ステータスを更新しました"
    redirect_to request.referer
  end

  private

    def order_params
      params.require(:order).permit(:status)
    end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<containar>
  <div class="row justify-content-center mt-5">
    <h3 class="mini-title">注文履歴詳細</h3>
  </div>

<div class="row justify-content-center mb-5">
  <div class="col-4">
    <table class="table table-borderless">
      <tbody>
        <tr>
          <th>購入者</th>
          <td><%= link_to @customer.full_name, admin_customer_path(@customer) %></td>
          </tr>
        <tr>
          <th>注文日</th>
          <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
        </tr>
        <tr>
          <th>配送先</th>
          <td>
            <p><%= "〒#{@order.postcode} #{@order.address}" %><br>
              <%= @order.address_name %>
            </p>
          </td>
        </tr>
        <tr>
          <th>支払い方法</th>
          <td><%= @order.pay_way_i18n %></td>
        </tr>
        <tr>
          <th>注文ステータス</th>
          <td>
            <%= form_with model: @order, url: admin_order_path, method: :patch do |f| %>
              <%= f.select :status, Order.statuses.keys.map { |k| [t("enums.order.status.#{k}"), k] } %>
              <%= f.submit '更新', class: "btn btn-success ml-4"%>
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="col-4 d-flex align-items-end ml-3">
    <table class="table table-bordered">
      <thead class="thead-dark text-center">
        <th>商品合計</th>
        <th>送料</th>
        <th>請求金額</th>
      </thead>
      <tbody class="text-right">
        <td>¥ <%= (@order.total_pay - @order.postage).to_s(:delimited) %></td>
        <td>¥ <%= @order.postage.to_s(:delimited) %></td>
        <td>¥ <%= @order.total_pay.to_s(:delimited) %></td>
      </tr>
    </table>
  </div>
</div>
<div class="row justify-content-center">
  <div class="col-8">
    <table class="table table-bordered table-background">
      <thead class="thead-dark text-center">
        <tr>
          <th style="width: 30%" class>商品</th>
          <th style="width: 20%">単価（税込）</th>
          <th style="width: 15%">数量</th>
          <th style="width: 15%">小計</th>
          <th style="width: 20%">製作ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @order.order_details.all.each do |order_detail| %>
          <tr>
            <td><%= order_detail.item.name %></td>
            <td class="text-right">¥ <%= (order_detail.item.price).to_s(:delimited) %>(税込み)</td>
            <td class="text-right"><%= order_detail.quantity %> 個</td>
            <td class="text-right">¥ <%= (order_detail.item.price*order_detail.quantity).to_s(:delimited) %></td>
            <td>
              <%= form_with model: order_detail, url: admin_order_detail_path(order_detail), method: :patch do |f| %>
                <%= f.select :production_status, OrderDetail.production_statuses.keys.map { |k| [t("enums.order_detail.production_status.#{k}"), k] } %>
                <%= f.submit '更新', class: "btn btn-success ml-2" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<containar>