config/routes.rb
Rails.application.routes.draw do


  devise_for :customers, path: :me, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }


  root to: 'public/homes#top'




  scope module: :public do
    # get 'customer/edit' => 'customers#edit'
    # patch 'customer/edit' => 'customers#update'
    get 'about' => 'homes#about'
    get 'orders/complete' => 'orders#complete'
    post 'orders/confirm' => 'orders#confirm'
    resources :orders, only: [:new, :index, :show, :create]
    resources :cart_items, only: [:index, :create, :update, :destroy]do
      delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    end
    resources :items, only: [:show, :index] do
      resources :reviews, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :deliveries, only: [:index, :destroy, :edit, :update, :create]
    resource :customers, only: [:show,:edit,:update] do
      get :favorites
    end

    patch 'customers/withdraw' => 'customers#withdraw'
    get 'customers/quit' => 'customers#quit'
  end



  namespace :admin do
    get '/' => 'homes#top'
    resources :orders, only: [:show, :update]
    resources :genres, only: [:index, :edit, :update, :create]
    resources :items, only: [:index, :show, :new, :edit, :update, :create]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :order_details, only: [:update]
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items

  validates :name, uniqueness: true, presence: true

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  layout 'admin/application'
  protect_from_forgery


  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:notice] = "新規ジャンル　登録完了"
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render "index"
    end
  end

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      flash[:notice] = "ジャンル編集完了"
      redirect_to admin_igenre_path
    else
      render "edit"
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/helpers/admins/genre_helper.rb
module Admins::GenreHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row justify-content-center mt-5 mb-3">
    <h3 class="mini-title">ジャンル編集</h3>
  </div>
  <%= render 'layouts/errors', obj: @genre %>

  <div class="text-right">
    <%= form_with model: @genre, url: admin_genre_path(@genre), method: :patch do |f| %>
      <div class="form-group row ml-lg-5">
        <%= f.label :name,"ジャンル", class: "col-lg-3" %>
        <%= f.text_field :name, class: "form-control col-lg-3" %>
        <div class="col-lg-3">
          <%= f.submit '編集登録',class:"btn btn-success btn-block" %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="row justify-content-center mt-5">
    <%= link_to "戻る", admin_genres_path %></div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row justify-content-center mt-5">
    <h3 class="mini-title">ジャンル追加</h3>
  </div>

  <%= render 'layouts/errors', obj: @genre %>

  <div class="text-right">
    <%= form_with model: @genre, url: admin_genres_path, method: :post do |f| %>
      <div class="form-group row ml-5">
        <%= f.label :name,"ジャンル", class: "col-lg-3" %>
        <%= f.text_field :name, class: "form-control col-lg-3" %>
        <div class="col-lg-3">
          <%= f.submit '新規追加',class:"btn btn-success btn-block" %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="row justify-content-center mt-5 mb-3">
    <h3 class="mini-title">ジャンル一覧</h3>
  </div>

  <div class="row text-center">
    <div class="col-lg-6 offset-3">
      <table class="table table-bordered">
        <thead class="thead-dark">
          <th>ジャンル名</th>
          <th>商品数</th>
          <th></th>
        </thead>
        <tbody>
          <% @genres.each do |genre| %>
            <tr>
              <td><%= genre.name %></td>
              <td><%= genre.items.count %></td>
              <td><%= link_to "編集する", edit_admin_genre_path(genre.id), class: "btn btn-success" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>