config/routes.rb
Rails.application.routes.draw do


  devise_for :customers, path: :me, controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, controllers: {
    sessions: "admin/sessions"
  }


  root to: 'public/homes#top'




  scope module: :public do
    # get 'customer/edit' => 'customers#edit'
    # patch 'customer/edit' => 'customers#update'
    get 'about' => 'homes#about'
    get 'orders/complete' => 'orders#complete'
    post 'orders/confirm' => 'orders#confirm'
    resources :orders, only: [:new, :index, :show, :create]
    resources :cart_items, only: [:index, :create, :update, :destroy]do
      delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    end
    resources :items, only: [:show, :index] do
      resources :reviews, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :deliveries, only: [:index, :destroy, :edit, :update, :create]
    resource :customers, only: [:show,:edit,:update] do
      get :favorites
    end

    patch 'customers/withdraw' => 'customers#withdraw'
    get 'customers/quit' => 'customers#quit'
  end



  namespace :admin do
    get '/' => 'homes#top'
    resources :orders, only: [:show, :update]
    resources :genres, only: [:index, :edit, :update, :create]
    resources :items, only: [:index, :show, :new, :edit, :update, :create]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :order_details, only: [:update]
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :item
  belongs_to :customer

  def subtotal
    item.with_tax_price * quantity
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :deliveries
  has_many :cart_items
  has_many :orders
  has_many :items, through: :cart_items
  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy


  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。' }
  validates :first_name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。' }
  VALID_POSTCODE_REGEX = /\A\d{7}\z/
  validates :postcode, presence: true, format: { with: VALID_POSTCODE_REGEX }
  validates :address, presence: true
  VALID_PHONE_NUMBER_REGEX = /\A0(\d{1}[-(]?\d{4}|\d{2}[-(]?\d{3}|\d{3}[-(]?\d{2}|\d{4}[-(]?\d{1})[-)]?\d{4}\z|\A0[5789]0[-]?\d{4}[-]?\d{4}\z/
  validates :phone_number, presence: true, format: { with: VALID_PHONE_NUMBER_REGEX }
  validates :email, presence: true, uniqueness: true
  validates :encrypted_password, presence: true

  def full_name
    self.last_name + self.first_name
  end

  def full_address
     '〒' + postcode + ' ' + address
  end

end

app/models/delivery.rb
class Delivery < ApplicationRecord

  belongs_to :customer

  VALID_POSTCODE_REGEX = /\A\d{7}\z/
  validates :postcode, presence: true, format: { with: VALID_POSTCODE_REGEX }
  validates :address, presence: true
  validates :address_name, presence: true



  def address_display
     '〒' + postcode + ' ' + address + ' ' + address_name
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :customer
  belongs_to :item

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items

  validates :name, uniqueness: true, presence: true

end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :customers, through: :cart_items
  has_many :order_details, dependent: :destroy
  has_many :orders, through: :order_details
  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy

  has_one_attached :image
  
  validates :name, presence: true, uniqueness: true
  validates :price, presence: true
  # validates :is_active, presence: true
  validates :description, presence: true

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      image.variant(resize_to_limit: [width, height]).processed
  end

  def with_tax_price
    (price* 1.1).floor
  end

  def favorited_by?(customer)
    favorites.exists?(customer_id: customer.id)
  end
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details, dependent: :destroy
  has_many :items, through: :order_details

  enum status: { waiting: 0, confirm: 1, production: 2, preparation: 3, sent: 4 }
  enum pay_way: { credit_card: 0, transfer: 1 }


  validates :pay_way, presence: true
  validates :postage, presence: true
  VALID_POSTCODE_REGEX = /\A\d{7}\z/
  validates :postcode, presence: true, format: { with: VALID_POSTCODE_REGEX }
  validates :address, presence: true
  validates :address_name, presence: true
  validates :total_pay, presence: true


  def status_display
    status_i18n
  end

  def payment_method_display
    payment_method_i18n
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item
  
  

  enum production_status: { impossible: 0, waiting: 1, making: 2, completion: 3 }
  
end

app/models/review.rb
class Review < ApplicationRecord

  belongs_to :customer
  belongs_to :item

  validates :star, presence: true
  validates :title, presence: true
  validates :body, presence: true
  # validates :, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # URLにadminが含まれるページはadminにログインしないと見れないよ
  before_action :authenticate_admin!, if: :admin_url

  def admin_url
    request.fullpath.include?("/admin")
  end

  # deviseの初期設定ではメールアドレスしか保存されないので、他の項目を増やす為の記述
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters

    if resource_class == Customer
      devise_parameter_sanitizer.permit(:sign_up, keys: [ :email, :last_name, :first_name, :last_name_kana, :first_name_kana, :postcode, :address, :phone_number, :password, :password_confirmation, :nick_name ])
      devise_parameter_sanitizer.permit(:sign_in,keys:[:email])
      devise_parameter_sanitizer.permit(:account_update,keys:[ :email, :last_name, :first_name, :last_name_kana, :first_name_kana, :postcode, :address, :phone_number, :nick_name])
    else
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email])
      devise_parameter_sanitizer.permit(:sign_in,keys:[:email])
      devise_parameter_sanitizer.permit(:account_update,keys:[:name,:email])
    end
  end


end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orderdetails_helper.rb
module Admin::OrderdetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admins/genre_helper.rb
module Admins::GenreHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_errors.html.erb
<div class="row justify-content-center mb-5">
  <div class="col-lg-8">
    <% if obj.errors.any? %>
      <div id="error_explanation">
        <div class="border border-danger">
          <h3 class="bg-danger text-center p-2"><%= pluralize(obj.errors.count, "件のエラー") %> </h3>
            <ul>
              <% obj.errors.full_messages.each do |message| %>
                <li class="list-unstyled text-center"><%= message %></li>
              <% end %>
            </ul>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_notice.html.erb
<% if notice %>
 <p id="notice" class="alert alert-warning m-0 text-center bg-dark" style="color:white;" ><%= notice %></p>
<% end %>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'admin', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
          <div class="row  mx-auto col-xl">
            <a class="navbar-brand" href="/"><%= image_tag 'logo-syefu (3)' %></a>
           <% if admin_signed_in? %>
           <!--ログインしている時-->
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                  <%=  link_to admin_items_path, class: 'nav-link' do %>
                    <i class="fas fa-beer"></i> 商品一覧
                  <% end %>
                </li>
                <li class="nav-item active">
                  <%= link_to admin_customers_path, class: 'nav-link' do %>
                    <i class="fas fa-beer"></i> 会員一覧
                  <% end %>
                </li>
                <li class="nav-item active">
                  <%=  link_to admin_path ,class: 'nav-link' do %>
                    <i class="fas fa-beer"></i> 注文履歴一覧
                  <% end %>
                </li>
                <li class="nav-item active">
                  <%= link_to admin_genres_path, class: 'nav-link' do %>
                    <i class="fas fa-beer"></i> ジャンル一覧
                  <% end %>
                </li>
                 <li class="nav-item active">
                  <%= link_to destroy_admin_session_path, method: :delete,class: 'nav-link' do %>
                    <i class="fas fa-sign-out-alt"></i> ログアウト
                  <% end %>
                </li>
              </ul>
            </div>
           <% else %>
           <!--ログインしていない時-->
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                  <%= link_to about_path, class: 'nav-link' do %>
                    <i class="fas fa-beer"></i> ABOUT
                  <% end %>
                </li>
                <li class="nav-item active">
                  <%= link_to items_path, class: 'nav-link' do %>
                    <i class="fas fa-heart"></i> PRODUCTS
                  <% end %>
                </li>
                <li class="nav-item active">
                  <%= link_to new_customer_registration_path, class: 'nav-link' do %>
                    <i class="fas fa-user-plus"></i> SIGN UP
                  <% end %>
                </li>
                <li class="nav-item active">
                  <%= link_to new_customer_session_path, class: 'nav-link' do %>
                    <i class="fas fa-sign-in-alt"></i> LOG IN
                  <% end %>
                </li>
              </ul>
            </div>
          <% end %>
          </div>
        </div>
      </nav>
    </header>

    <div id="flash-success">
      <%=render "layouts/notice" %>
    </div>

    <%= yield %>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>